spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 333503065838-coh3lvkb3hu33r728skumdndvn25evsv.apps.googleusercontent.com
            client-secret: ...
            scope:
              - email
              - profile

jwt:
  issuer: fatal_linverno@naver.com
  secret_key: study-springboot