server:
  port: 8888

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true